package br.com.giex.hibernate;
// Generated 25/10/2012 10:35:04 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCredorXml generated by hbm2java
 */
public class TbCredorXml implements java.io.Serializable {

    private BigDecimal idXml;
    private TbCredor tbCredor;
    private BigDecimal idOrdem;
    private Clob xmlC;
    private Boolean ativoN;
    private Set tbCredorLogProcessamentos = new HashSet(0);

    public TbCredorXml() {
    }

    public TbCredorXml(BigDecimal idXml, TbCredor tbCredor, BigDecimal idOrdem) {
        this.idXml = idXml;
        this.tbCredor = tbCredor;
        this.idOrdem = idOrdem;
    }

    public TbCredorXml(BigDecimal idXml, TbCredor tbCredor, BigDecimal idOrdem, Clob xmlC, Boolean ativoN, Set tbCredorLogProcessamentos) {
        this.idXml = idXml;
        this.tbCredor = tbCredor;
        this.idOrdem = idOrdem;
        this.xmlC = xmlC;
        this.ativoN = ativoN;
        this.tbCredorLogProcessamentos = tbCredorLogProcessamentos;
    }

    public BigDecimal getIdXml() {
        return this.idXml;
    }

    public void setIdXml(BigDecimal idXml) {
        this.idXml = idXml;
    }

    public TbCredor getTbCredor() {
        return this.tbCredor;
    }

    public void setTbCredor(TbCredor tbCredor) {
        this.tbCredor = tbCredor;
    }

    public BigDecimal getIdOrdem() {
        return this.idOrdem;
    }

    public void setIdOrdem(BigDecimal idOrdem) {
        this.idOrdem = idOrdem;
    }

    public Clob getXmlC() {
        return this.xmlC;
    }

    public void setXmlC(Clob xmlC) {
        this.xmlC = xmlC;
    }

    public Boolean getAtivoN() {
        return this.ativoN;
    }

    public void setAtivoN(Boolean ativoN) {
        this.ativoN = ativoN;
    }

    public Set getTbCredorLogProcessamentos() {
        return this.tbCredorLogProcessamentos;
    }

    public void setTbCredorLogProcessamentos(Set tbCredorLogProcessamentos) {
        this.tbCredorLogProcessamentos = tbCredorLogProcessamentos;
    }
}
