package br.com.giex.hibernate;
// Generated 25/10/2012 10:35:04 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCredorLoteProcessamento generated by hbm2java
 */
public class TbCredorLoteProcessamento implements java.io.Serializable {

    private Long idLote;
    private TbCredor tbCredor;
    private Date dataInicioD;
    private Date dataFimD;
    private String logC;
    private Set tbCredorLogProcessamentos = new HashSet(0);

    public TbCredorLoteProcessamento() {
    }

    public TbCredorLoteProcessamento(Long idLote, TbCredor tbCredor, Date dataInicioD) {
        this.idLote = idLote;
        this.tbCredor = tbCredor;
        this.dataInicioD = dataInicioD;
    }

    public TbCredorLoteProcessamento(Long idLote, TbCredor tbCredor, Date dataInicioD, Date dataFimD, String logC, Set tbCredorLogProcessamentos) {
        this.idLote = idLote;
        this.tbCredor = tbCredor;
        this.dataInicioD = dataInicioD;
        this.dataFimD = dataFimD;
        this.logC = logC;
        this.tbCredorLogProcessamentos = tbCredorLogProcessamentos;
    }

    public Long getIdLote() {
        return this.idLote;
    }

    public void setIdLote(Long idLote) {
        this.idLote = idLote;
    }

    public TbCredor getTbCredor() {
        return this.tbCredor;
    }

    public void setTbCredor(TbCredor tbCredor) {
        this.tbCredor = tbCredor;
    }

    public Date getDataInicioD() {
        return this.dataInicioD;
    }

    public void setDataInicioD(Date dataInicioD) {
        this.dataInicioD = dataInicioD;
    }

    public Date getDataFimD() {
        return this.dataFimD;
    }

    public void setDataFimD(Date dataFimD) {
        this.dataFimD = dataFimD;
    }

    public String getLogC() {
        return this.logC;
    }

    public void setLogC(String logC) {
        this.logC = logC;
    }

    public Set getTbCredorLogProcessamentos() {
        return this.tbCredorLogProcessamentos;
    }

    public void setTbCredorLogProcessamentos(Set tbCredorLogProcessamentos) {
        this.tbCredorLogProcessamentos = tbCredorLogProcessamentos;
    }
}
