package br.com.giex.hibernate;
// Generated 25/10/2012 10:35:04 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbCredorLogProcessamento generated by hbm2java
 */
public class TbCredorLogProcessamento implements java.io.Serializable {

    private Long idLog;
    private TbCredor tbCredor;
    private TbCredorXml tbCredorXml;
    private TbCredorLoteProcessamento tbCredorLoteProcessamento;
    private Date dataInicioD;
    private Date dataFimD;
    private String logC;
    private BigDecimal countN;

    public TbCredorLogProcessamento() {
    }

    public TbCredorLogProcessamento(Long idLog, TbCredor tbCredor, TbCredorXml tbCredorXml, TbCredorLoteProcessamento tbCredorLoteProcessamento, Date dataInicioD) {
        this.idLog = idLog;
        this.tbCredor = tbCredor;
        this.tbCredorXml = tbCredorXml;
        this.tbCredorLoteProcessamento = tbCredorLoteProcessamento;
        this.dataInicioD = dataInicioD;
    }

    public TbCredorLogProcessamento(Long idLog, TbCredor tbCredor, TbCredorXml tbCredorXml, TbCredorLoteProcessamento tbCredorLoteProcessamento, Date dataInicioD, Date dataFimD, String logC, BigDecimal countN) {
        this.idLog = idLog;
        this.tbCredor = tbCredor;
        this.tbCredorXml = tbCredorXml;
        this.tbCredorLoteProcessamento = tbCredorLoteProcessamento;
        this.dataInicioD = dataInicioD;
        this.dataFimD = dataFimD;
        this.logC = logC;
        this.countN = countN;
    }

    public Long getIdLog() {
        return this.idLog;
    }

    public void setIdLog(Long idLog) {
        this.idLog = idLog;
    }

    public TbCredor getTbCredor() {
        return this.tbCredor;
    }

    public void setTbCredor(TbCredor tbCredor) {
        this.tbCredor = tbCredor;
    }

    public TbCredorXml getTbCredorXml() {
        return this.tbCredorXml;
    }

    public void setTbCredorXml(TbCredorXml tbCredorXml) {
        this.tbCredorXml = tbCredorXml;
    }

    public TbCredorLoteProcessamento getTbCredorLoteProcessamento() {
        return this.tbCredorLoteProcessamento;
    }

    public void setTbCredorLoteProcessamento(TbCredorLoteProcessamento tbCredorLoteProcessamento) {
        this.tbCredorLoteProcessamento = tbCredorLoteProcessamento;
    }

    public Date getDataInicioD() {
        return this.dataInicioD;
    }

    public void setDataInicioD(Date dataInicioD) {
        this.dataInicioD = dataInicioD;
    }

    public Date getDataFimD() {
        return this.dataFimD;
    }

    public void setDataFimD(Date dataFimD) {
        this.dataFimD = dataFimD;
    }

    public String getLogC() {
        return this.logC;
    }

    public void setLogC(String logC) {
        this.logC = logC;
    }

    public BigDecimal getCountN() {
        return countN;
    }

    public void setCountN(BigDecimal countN) {
        this.countN = countN;
    }
}